### PR TITLE
Add sphinx link

### LINKED ISSUE #10: Add documentation
Add installation instructions, developer guide and usage

### PR DESCRIPTION
**Pull request by PhilipMay**
Add link to the Sphinx API doc to the `README.md`.
Fixes #10

### CODE REVIEW

**Comment by PhilipMay** [comment]
@axeoman @deztructor 
PR is ready to be merged.

**Review by axeoman — CHANGES_REQUESTED** [review]
Thanks for this addition :+1:
However, I would like to ask you to squash both commits into a single one and call it with a capital letter.

**Comment by PhilipMay** [comment]
>  However, I would like to ask you to squash both commits into a single one and call it with a capital letter.

Done

**Review by VachaShah — APPROVED** [review]
Thank you very much @PhilipMay for adding this!

**Pull request merged**
