### PR TITLE
Add DCO check

### LINKED ISSUE #80: Ensure DCO Workflow Check
Coming from https://github.com/opensearch-project/project-meta/issues/17

A Developer Certificate of Origin is required on commits in the OpenSearch-Project.

See [doc.yml](https://github.com/opensearch-project/.github/blob/main/workflow/dco.yml) for an example workflow.  Ensure CONTRIBUTING.md to has a section on the DCO per the [project template](https://github.com/opensearch-project/.github/blob/main/CONTRIBUTING.md#developer-certificate-of-origin). 

- [x] DCO Check Workflow
- [x] CONTRIBUTING.md DCO Section

### PR DESCRIPTION
**Pull request by CEHENKLE**
Signed-off-by: CEHENKLE <henkle@amazon.com>

### Description
Add DCO check
 
### Issues Resolved

#80 
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peternied** [comment]
+Maintainers @rushiagr @Shephalimittal @axeoman @deztructor looks like CI is broken, can we get help merging this change?

**Review by peternied — APPROVED** [review]
I see that this PR has the DCO check run against it, thanks for doing this @CEHENKLE

**Review by axeoman — APPROVED** [review]

**Comment by axeoman** [comment]
Something wrong with one of the integration tests, but IIUC should not be related.

**Comment by CEHENKLE** [comment]
Thanks @axeoman .  I took a look, and it definitely doesn't seem related.  @opensearch-project/clients If I can get one more review, I think it's safe to merge in.

Thanks,
/C

**Review by saratvemulapalli — APPROVED** [review]

**Pull request merged**
