### PR TITLE
Enhance generator to update changelog only if generated code differs from existing

### PR DESCRIPTION
**Pull request by saimedhi**
### Description
Enhance generator to update changelog only if generated code differs from existing code. 

### Issues Resolved
https://github.com/opensearch-project/opensearch-py/pull/680#issuecomment-1966865315

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]
I'll merge, but this seems a little complicated. 

Would it make things simpler to do the `rm -rf`, generate the code into `opensearchpy`, then look at `git status` to see what has changed?

**Comment by saimedhi** [comment]
> I'll merge, but this seems a little complicated.
> 
> Would it make things simpler to do the `rm -rf`, generate the code into `opensearchpy`, then look at `git status` to see what has changed?

I'll give that approach a try. Just want to make sure files like .pycache won't cause any issues.

**Comment by dblock** [comment]
> > I'll merge, but this seems a little complicated.
> > Would it make things simpler to do the `rm -rf`, generate the code into `opensearchpy`, then look at `git status` to see what has changed?
> 
> I'll give that approach a try. Just want to make sure files like .pycache won't cause any issues.

Anything generated should be in `.gitignore`.

**Comment by dblock** [comment]
> I'll give that approach a try.

Btw, I think it's not important _what_ has changed. The workflow that runs this check could generate the code, then check whether anything has changed, and only if something has generate the changelog. Then try opening the PR which would do nothing if there were no changes.

**Pull request merged**
