### PR TITLE
Add license header check workflow

### LINKED ISSUE #200: [FEATURE] Add license header check for new files
### Is your feature request related to a problem?
Incoming new files must be checked for [OpenSearch licenses](https://github.com/opensearch-project/.github/blob/main/CONTRIBUTING.md#license-headers)

### What solution would you like?
A similar approach to https://github.com/opensearch-project/opensearch-net/blob/main/.github/check-license-headers.sh

### PR DESCRIPTION
**Pull request by harshavamsi**
### Description
Adds license header check for all files.

Here's the workflow running on my fork -- https://github.com/harshavamsi/opensearch-py/actions/runs/3069009234

The PR also updates the license headers according to the current standard -- https://github.com/opensearch-project/.github/blob/main/CONTRIBUTING.md#python-ruby-shell

### Issues Resolved
Closes #200 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — DISMISSED** [review]

**Review by VachaShah — COMMENTED** [review]
Thank you for adding this @harshavamsi! I might be missing something here but there is a script in `utils/license-headers.py` which also checks for licenses. Do we need the new script as well or can be combined into one?

**Comment by harshavamsi** [comment]
> Thank you for adding this @harshavamsi! I might be missing something here but there is a script in `utils/license-headers.py` which also checks for licenses. Do we need the new script as well or can be combined into one?

@VachaShah I took a look at that. I am not sure why it does not trigger a failure run when licenses are not present. I wanted to bring in a workflow across all clients with this.

**Comment by VachaShah** [comment]
> 

Got it. Can we see if it is not used anymore since you added this workflow? If the same work is done by the new workflow, maybe we can remove it?

**Comment by dblock** [comment]
@harshavamsi Want to finish this?

**Comment by dblock** [comment]
I see we're rolling out our own shell scripts? Is there really no good python library to check headers? e.g. https://pypi.org/project/license-header-check/?

**Comment by wbeckler** [comment]
@harshavamsi should we close this?

**Pull request closed without merging**
