### PR TITLE
Adds various client docs within Opensearch client

### PR DESCRIPTION
**Pull request by jaydm26**
### Description
This PR adds documentation to Sphinx for the clients within the Opensearch client. To include this, the docs were slightly restructured.

### Issues Resolved
Addresses #171 by adding docs for clients included within the Opensearch client.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by harshavamsi** [comment]
LGTM! Thanks so much for this!

@VachaShah @wbeckler let's get this merged?

**Review by VachaShah — COMMENTED** [review]
Thank you @jaydm26 for adding this! I built the Sphinx website on my local but I do not see these changes being incorporated. Is there something missing?

**Comment by harshavamsi** [comment]
@VachaShah I see them. 

image

**Comment by VachaShah** [comment]
> @VachaShah I see them.
> 
> image

Oh my bad! I think I was looking at the wrong place. Thanks!

**Review by VachaShah — APPROVED** [review]

**Review by dblock — APPROVED** [review]

**Pull request merged**
