### PR TITLE
fix proxy.md

### PR DESCRIPTION
**Pull request by jiangying000**
related: https://github.com/opensearch-project/opensearch-py/issues/821

### CODE REVIEW

**Comment by dblock** [comment]
Why doesn't it work with the default connection class?

**Comment by dblock** [comment]
> RequestsHttpConnection

There are multiple connection classes, see https://github.com/opensearch-project/opensearch-py/blob/9dd7bf7cb3e80b98fcc256edb9c49cf89202f522/guides/connection_classes.md.

The default is `Urllib3HttpConnection` for synchronous scenarios. The change you are proposing switching a non-working proxy implementation in `Urllib3HttpConnection` to a working proxy implementation in `RequestsHttpConnection`, so I don't think this is the right fix, aside of the documentation someone needs to actually fix the problem for proxy support in `Urllib3HttpConnection`.

**Comment by jiangying000** [comment]
Agree, this is not a fix to #821 , just a temporary fix to the doc

At least Users can get what they want by following the doc with this change

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
I agree, I'll merge this.

**Pull request merged**
