### PR TITLE
Bump version to 2.5.0

### LINKED ISSUE #695: New opensearch py release
We would like to update [ForceMerge()](https://github.com/opensearch-project/opensearch-benchmark/blob/main/osbenchmark/worker_coordinator/runner.py#L674) Runner from OpenSearch Benchmark with latest api https://github.com/opensearch-project/opensearch-py/pull/660 . This will help workloads like vector search to use force merge as async operation since force merge takes hours to complete for large dataset.

I created a workaround in local fork https://github.com/VijayanB/opensearch-benchmark/commit/b73d3a9de2b4dbc2d3a5bc071c1d47167ae5aec6 

This is blocker for vector search benchmark. It will be great if we could get this change from upstream instead of cherry-picking.

### PR DESCRIPTION
**Pull request by saimedhi**
### Description
Bump version to 2.5.0

### Issues Resolved
Closes #695 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by saimedhi** [comment]
@VachaShah, @dblock please take a look. 

Also, can you confirm if the version specified in .github/workflows/unified-release.yml and opensearchpy/_version.py is correct as 2.5.0?

**Review by harshavamsi — DISMISSED** [review]

**Comment by harshavamsi** [comment]
Link checker looks like a bug, should be fine.

**Comment by dblock** [comment]
Merge?

**Comment by saimedhi** [comment]
> Merge?

@dblock, should I update the version of opensearch-py in the following locations?

1. [benchmarks/poetry.lock](https://github.com/opensearch-project/opensearch-py/blob/main/benchmarks/poetry.lock#L518)
2. [samples/poetry.lock](https://github.com/opensearch-project/opensearch-py/blob/main/samples/poetry.lock#L534)

**Comment by saimedhi** [comment]
> > Merge?
> 
> @dblock, should I update the version of opensearch-py in the following locations?
> 
> 1. [benchmarks/poetry.lock](https://github.com/opensearch-project/opensearch-py/blob/main/benchmarks/poetry.lock#L518)
> 2. [samples/poetry.lock](https://github.com/opensearch-project/opensearch-py/blob/main/samples/poetry.lock#L534)

# Read for review

**Review by VijayanB — APPROVED** [review]

**Comment by VijayanB** [comment]
@VachaShah Can this be merged? Looking forward for 2.5

**Review by harshavamsi — APPROVED** [review]

**Pull request merged**
