### PR TITLE
Move security api from plugins to clients

### PR DESCRIPTION
**Pull request by florianvazelle**
### Description
I move the `SecurityClient` from the plugins directory to the clients directory, accordingly to the @saimedhi comment (https://github.com/opensearch-project/opensearch-py/pull/399#issuecomment-1642789791).
> All the security features are considered as part of core features of OS.

### CODE REVIEW

**Comment by dblock** [comment]
How does this impact end-users? Anything I'd have to change in my code when upgrading?

**Comment by dblock** [comment]
> You'll just have to change the import paths if you imported the client directly from plugins (`from opensearchpy.plugins import security` into `from opensearchpy.clients import security`).

That's a breaking change :( Is there a way to proxy the old to the new so we don't have to bump the major version?

**Comment by saimedhi** [comment]
> > You'll just have to change the import paths if you imported the client directly from plugins (`from opensearchpy.plugins import security` into `from opensearchpy.clients import security`).
> 
> That's a breaking change :( Is there a way to proxy the old to the new so we don't have to bump the major version?

@dblock This change is not yet released.

**Comment by dblock** [comment]
> > > You'll just have to change the import paths if you imported the client directly from plugins (`from opensearchpy.plugins import security` into `from opensearchpy.clients import security`).
> > 
> > 
> > That's a breaking change :( Is there a way to proxy the old to the new so we don't have to bump the major version?
> 
> @dblock This change is not yet released.

Oh! Good.

**Review by dblock — APPROVED** [review]

**Pull request merged**
