### PR TITLE
Fixed Sigv4 Signing for Managed Service and Async OpenSearch

### PR DESCRIPTION
**Pull request by nhtruong**
Signed-off-by: Theo Truong <theotr@amazon.com>

### Issues Resolved
closes https://github.com/opensearch-project/opensearch-py/issues/278
closes https://github.com/opensearch-project/opensearch-py/issues/272

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
Needs tests please?

**Comment by VachaShah** [comment]
Thank you @nhtruong! Can you fix the lint that is causing the CI to fail?

**Review by harshavamsi — APPROVED** [review]
LGTM!

**Review by dblock — APPROVED** [review]
I’ll approve but we do need a test for the query string problem.

**Review by VachaShah — APPROVED** [review]

**Pull request merged**
