### PR TITLE
Added a utf-8 header to all .py files.

### PR DESCRIPTION
**Pull request by dblock**
### Description

Consistently add a utf-8 header to all .py files.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by VachaShah — APPROVED** [review]

**Comment by jayaddison** [comment]
@dblock an extremely pedantic note while reviewing changes from [v2.3.2](https://github.com/opensearch-project/opensearch-py/commit/2f57661ebb7c692142c4667f39ac6a2124620f8d) to [v2.4.2](https://github.com/opensearch-project/opensearch-py/commit/103bc8948616dce57719ad089584e8e706427434) - it looks like a couple of these encoding declarations dropped out when bcfef113c43f74c41dec9c43ba54d6e00cc17c90 was committed ([`run_tests.py` here](https://github.com/opensearch-project/opensearch-py/commit/bcfef113c43f74c41dec9c43ba54d6e00cc17c90#diff-4b8c99b4fdb3ecef019b445e8febaa794d6a6cefb451ab75f7e2e804e4092577L2) and [`generate-api.py` here](https://github.com/opensearch-project/opensearch-py/commit/bcfef113c43f74c41dec9c43ba54d6e00cc17c90#diff-10fce91a9702f8e056c52b941a704932da46903d1646b6ad10aa1fbfa3d91ae8L2)).

Hopefully not a problem in itself, but perhaps an indication of some utility/process that should have left those lines intact.

**Comment by dblock** [comment]
> @dblock an extremely pedantic note while reviewing changes from [v2.3.2](https://github.com/opensearch-project/opensearch-py/commit/2f57661ebb7c692142c4667f39ac6a2124620f8d) to [v2.4.2](https://github.com/opensearch-project/opensearch-py/commit/103bc8948616dce57719ad089584e8e706427434) - it looks like a couple of these encoding declarations dropped out when [bcfef11](https://github.com/opensearch-project/opensearch-py/commit/bcfef113c43f74c41dec9c43ba54d6e00cc17c90) was committed ([`run_tests.py` here](https://github.com/opensearch-project/opensearch-py/commit/bcfef113c43f74c41dec9c43ba54d6e00cc17c90#diff-4b8c99b4fdb3ecef019b445e8febaa794d6a6cefb451ab75f7e2e804e4092577L2) and [`generate-api.py` here](https://github.com/opensearch-project/opensearch-py/commit/bcfef113c43f74c41dec9c43ba54d6e00cc17c90#diff-10fce91a9702f8e056c52b941a704932da46903d1646b6ad10aa1fbfa3d91ae8L2)).
> 
> Hopefully not a problem in itself, but perhaps an indication of some utility/process that should have left those lines intact.

Yep, this is a problem :(

**Comment by dblock** [comment]
@jayaddison I opened https://github.com/opensearch-project/opensearch-py/issues/613. Maybe you want to tackle it? Ideally there's a pylint rule/linter that ensures these are present everywhere, or maybe we'll need to write one.

**Comment by jayaddison** [comment]
Possibly, yep - I'll follow along in that thread (and have asked a question about the reason for the coding declarations).

**Pull request merged**
