### PR TITLE
Expanded type coverage to benchmarks, samples and tests.

### PR DESCRIPTION
**Pull request by dblock**
### Description

Expanded type coverage to benchmarks, samples and tests.

### Issues Resolved

Closes https://github.com/opensearch-project/opensearch-py/issues/564.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
@saimedhi I think this is 🟢

**Review by VachaShah — APPROVED** [review]
LGTM

**Comment by dblock** [comment]
@saimedhi good with you?

**Comment by dblock** [comment]
I think @saimedhi is OOO, will merge (please add more comments and I can take of them later if needed), thanks @VachaShah for a CR.

**Pull request merged**
