### PR TITLE
Bump version to 2.3.1

### LINKED ISSUE #472: [PROPOSAL] Cut a new release including #470
### What are you proposing?
I would love it if the project cut a new release including the fix from #470!

### What users have asked for this feature?
Me, I guess? Kinda want to finish some internal documentation 😅 .

Thanks!

### PR DESCRIPTION
**Pull request by saimedhi**
### Description
Bump version to 2.3.1

### Issues Resolved
Closes #472 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by VachaShah** [comment]
For future, you can create this PR against `main` and then backport it to `2.3` branch using the backport workflow instead of manually creating against 2.3.

**Review by VachaShah — COMMENTED** [review]
Can you fix the merge conflicts in this PR?

**Comment by saimedhi** [comment]
> Can you fix the merge conflicts in this PR?

done

**Review by VachaShah — APPROVED** [review]

**Comment by VachaShah** [comment]
@saimedhi Once 2.3.1 is released, lets update the main branch to version `2.4.0` so we have it ready for the next release.

**Pull request merged**
