### PR TITLE
feat: Added pool_maxsize in RequestsHttpConnection

### PR DESCRIPTION
**Pull request by Neckbuster**
### Description
Provides custom connection pool size for RequestHttpConnection transport class
### Issues Resolved
Closes proposal/issue #203

### CODE REVIEW

**Comment by dblock** [comment]
Would it make sense to provide an `http_adapter_options` structure that wraps all the other options available in HTTPAdapter?

**Comment by harshavamsi** [comment]
@Neckbuster the implementation looks fine to me. Can you sign off your commit with `-s` to allow DCO to pass? Also, can you add a unit test to ensure this works against our tests?

**Review by dblock — CHANGES_REQUESTED** [review]
Totally missed the updates to this. Let's add some documentation to https://github.com/opensearch-project/opensearch-py/blob/main/GETTING_STARTED.md for it before merging?

**Comment by Neckbuster** [comment]
> Totally missed the updates to this, apologies. Let's add some documentation to https://github.com/opensearch-project/opensearch-py/blob/main/GETTING_STARTED.md for it before merging?

Thanks @dblock Have updated documentation info, please have a look.

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
@harshavamsi @VachaShah 2nd pls? Let's merge this?

**Pull request merged**
