### PR TITLE
Fixed timeout argument in Transport

### PR DESCRIPTION
**Pull request by borisevich-a-v**
### Description
Fixed bug https://github.com/opensearch-project/opensearch-py/issues/809

### Issues Resolved
- Timeout argument in Transport.perform_request is not used, because it is redefined just below

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by borisevich-a-v** [comment]
Sorry, I cannot satisfy DCO due to my account settings. But PR is signed off correctly

**Comment by borisevich-a-v** [comment]
> Add a test please?
Sure, I'll add

> I am not sure what the issue with DCO is, why can’t it be fixed with your account?
Hope it will not be a problem. I have two Github accounts. And for this one I have secondary email address for a while.

**Comment by borisevich-a-v** [comment]
Added test and also fix the same problem with ignore, if you don't mind

**Comment by borisevich-a-v** [comment]
@dblock 
Added tests, fixed AsyncTransport as well
Tried to add code in the same code style, if there is any mistakes let me know

**Comment by dblock** [comment]
> > I am not sure what the issue with DCO is, why can’t it be fixed with your account?
> 
> Hope it will not be a problem. I have two GitHub accounts due to job requirements. And for this one I have secondary email address for a while.

I am not supposed to approve PRs without passing DCO :) Let's try to fix it.

You can configure the email address per repo. I do this routinely on a work computer for anything non-work.

```
git config user.name ...
git config user.email ...
```

Does this work?

**Review by dblock — APPROVED** [review]

**Comment by borisevich-a-v** [comment]
> Does this work?

The problem was with my emails. I have satisfied DCO :)

**Review by dblock — APPROVED** [review]
Thanks for fixing this!

**Pull request merged**
