### PR TITLE
change black target-version to py33

### PR DESCRIPTION
**Pull request by PhilipMay**
fix for #119

### CODE REVIEW

**Comment by dtaivpp** [comment]
I wonder if we need to run black locally and check in the 4 files it wants to fix. Sorry I would have recommended that earlier if I knew that was the case.  @VijayanB can you confirm this?

**Comment by PhilipMay** [comment]
CI is grean. IMO it can be merged please. @dtaivpp

**Comment by dtaivpp** [comment]
@PhilipMay  I am actually not a reviewer on this repo but maybe @VijayanB @Shivamdhar can weigh in.

**Review by VijayanB — APPROVED** [review]
LGTM. Thanks

**Review by dtaivpp — APPROVED** [review]
Looks good to me as well. Python 2.7 no longer is supported by the Python Software Foundation (PSF) so makes sense to deprecate.

**Comment by PhilipMay** [comment]
Ok. Cool, thanks.
2 positive reviews.
Next step: Merge? :-)

**Pull request merged**
