### PR TITLE
Generate cluster client from API specs

### PR DESCRIPTION
**Pull request by saimedhi**
### Description
Generate cluster client from API specs

### Issues Resolved
related to #477  

### cluster.health   -    ensure_node_commissioned param should not be present

- need to be corrected in spec. 

`https://localhost:9200/_cluster/health?ensure_node_commissioned=true`
{
"error": {
"root_cause": [
{
"type": "illegal_argument_exception",
"reason": "request [/_cluster/health] contains unrecognized parameter: [ensure_node_commissioned] -> did you mean [ensure_node_weighed_in]?"
}
],
"type": "illegal_argument_exception",
"reason": "request [/_cluster/health] contains unrecognized parameter: [ensure_node_commissioned] -> did you mean [ensure_node_weighed_in]?"
},
"status": 400
}
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]
Any reason not to generate all remaining APIs in one go?

**Comment by dblock** [comment]
> need to be corrected in spec

Are you doing this? Opening issues?

**Comment by saimedhi** [comment]
> Opening issues?

yes, I am opening issues in [opensearch-api-specification](https://github.com/opensearch-project/opensearch-api-specification) repo

**Comment by saimedhi** [comment]
> Any reason not to generate all remaining APIs in one go?

I can generate all at once, but it'll be easier to spot small issues or mistakes in the generated client with smaller PRs.

**Pull request merged**
