### PR TITLE
Added new test case for bulk delete

### LINKED ISSUE #873: [BUG] Bulk operation throwing 'action_request_validation_exception" when doing bulk delete.
### What is the bug?
When using helpers.bulk to delete objects in bulk, the helpers.bulk function throws the exception shown below. I noticed there are no examples of doing a delete in the documentation. 

```
raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
opensearchpy.exceptions.RequestError: RequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: index is missing;')
```

### How can one reproduce the bug?
Use this code. 

```
docs = [{"delete": {"_index": "<index name", "_id": "<id>"}}]           
helpers.bulk(client, docs)
```
      
### What is the expected behavior?
The bulk function should be able to delete objects in bulk. The same request works fine from postman when going directly against the opensearch '_bulk' API. 

### What is your host/environment?
OS: MacOS 14.7.1 (23H222)
Python 3.12.3
opensearch-py: 2.8.0

### PR DESCRIPTION
**Pull request by Harshil-Jani**
### Description

Added new test case for bulk delete

### Issues Resolved

closes #873 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
Thanks! Try fixing it?

**Comment by Harshil-Jani** [comment]
Sure. Will spend some time this weekend to check if I can find anything.

**Comment by Harshil-Jani** [comment]
Updated the test case with correct usage. It's working as expected. Not a bug anymore.

**Review by dblock — APPROVED** [review]
What was the usage mistake? Do we need to make the documentation cleaerer?

**Pull request merged**
