### PR TITLE
[CCI][GUIDE] Added Guide for Snapshot API(snapshot.md)

### PR DESCRIPTION
**Pull request by roma2023**
### Description
Added Snapshot Actions Guide (guides/snapshot.md) with code examples

### Issues Resolved
issue #406 resolved

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
Needs actual content in snapshot.md :)

**Comment by roma2023** [comment]
Ohhh I see, the changes weren't properly saved. It's fixed now!

**Review by dblock — COMMENTED** [review]
Can we link this from somewhere?

**Comment by roma2023** [comment]
Maybe we can add a link in USER_GUIDE.md as well as links to other guides

**Comment by wbeckler** [comment]
@roma2023 feel free to add those links

**Comment by roma2023** [comment]
So, I am going to update USER_GUIDE.md, should I open a new PR for it to specify the change?

**Comment by dblock** [comment]
> So, I am going to update USER_GUIDE.md, should I open a new PR for it to specify the change?

Do it part of this PR!

**Comment by dblock** [comment]
Sorry for being late to this, let's finish it? We've done some reorganizing, so rebase this change please. I also added working samples to samples, want to add a working piece of code into this PR?

**Comment by roma2023** [comment]
Yes, let's finish this. I can use working pieces of the 'Hello World' sample.

**Comment by saimedhi** [comment]
@roma2023, Could you please make the requested changes when you have a moment? Thank you!

**Comment by roma2023** [comment]
Please check new PR #486 and let's finish this task. I apologize for the delay.

**Pull request closed without merging**
